#!/bin/bash
# Nakama Development Environment Setup Script
# Initializes all necessary environment variables, configurations, and dependencies

set -e

echo "🚀 Nakama Development Environment Setup"
echo "========================================"

# Step 1: Set up environment variables
echo ""
echo "[1/6] Setting up environment variables..."

export STASH_URL="http://localhost:8080"
export STASH_DB_URL="postgres://stash:changeme@localhost:5432/stash"
export STASH_EMBEDDING_MODEL="openai:text-embedding-3-small"
export STASH_OPENAI_API_KEY="your-openai-api-key-here"
export STASH_OLLAMA_URL="http://localhost:11434"
export STASH_OLLAMA_MODEL="deepseek-r1:1.5b"

# Create .env file for persistence
cat > .env << EOF
# Nakama Environment Configuration
# Generated by setup-dev.sh on $(date '+%Y-%m-%d %H:%M:%S')

STASH_URL=http://localhost:8080
STASH_DB_URL=postgres://stash:changeme@localhost:5432/stash
STASH_EMBEDDING_MODEL=openai:text-embedding-3-small
STASH_OPENAI_API_KEY=your-openai-api-key-here
STASH_OLLAMA_URL=http://localhost:11434
STASH_OLLAMA_MODEL=deepseek-r1:1.5b
EOF

echo "✓ Environment variables configured in .env file"

# Step 2: Create Nakama config directories
echo ""
echo "[2/6] Creating configuration directories..."

mkdir -p ~/.nakama_config
echo "✓ ~/.nakama_config ready"

mkdir -p ~/.lancedb
echo "✓ ~/.lancedb ready"

mkdir -p ~/.nakama_logs
echo "✓ ~/.nakama_logs ready"

# Step 3: Install Node.js dependencies
echo ""
echo "[3/6] Installing Node.js dependencies..."
pnpm install
echo "✓ pnpm install completed"

# Step 4: Start Stash service (Docker)
echo ""
echo "[4/6] Starting Stash service (Docker)..."
if command -v docker &> /dev/null; then
    if [ -f "stash-docker-compose.yml" ]; then
        docker-compose -f stash-docker-compose.yml up -d 2>&1 || echo "⚠ Docker compose may already be running or had issues"
        echo "✓ Stash service started (waiting for PostgreSQL to be ready)..."
        sleep 5
    else
        echo "⚠ stash-docker-compose.yml not found"
    fi
else
    echo "⚠ Docker not found - skipping Stash docker setup"
fi

# Step 5: Check Ollama and pull model
echo ""
echo "[5/6] Checking Ollama..."
if command -v ollama &> /dev/null; then
    if ollama list 2>&1 | grep -q "deepseek-r1:1.5b"; then
        echo "✓ deepseek-r1:1.5b model already available"
    else
        echo "Pulling deepseek-r1:1.5b model (this may take a while)..."
        ollama pull deepseek-r1:1.5b 2>&1
    fi
else
    echo "⚠ Ollama not installed - download from https://ollama.ai"
fi

# Step 6: Build Rust Tauri backend
echo ""
echo "[6/6] Building Rust backend..."
if command -v cargo &> /dev/null; then
    echo "Running cargo check with swiftide_integration feature..."
    (cd src-tauri && cargo check --features swiftide_integration 2>&1) || echo "⚠ Rust build encountered issues (check native dependencies like NASM)"
    echo "✓ Rust backend build check complete"
else
    echo "⚠ Cargo not found - install Rust from https://rustup.rs"
fi

echo ""
echo "========================================"
echo "✅ Setup Complete!"
echo ""
echo "Next steps:"
echo "  1. Ensure Ollama is running: ollama run deepseek-r1:1.5b"
echo "  2. Start development: pnpm tauri dev"
echo "  3. Open Index Manager (📚 button) to test RAG functionality"
echo ""
echo "For Stash integration, ensure Docker services are running."